version: '3.8'

services:
  nginx:
    restart: "no"
    environment:
      - NGINX_MOD=development
    networks:
      - default

  backend:
    build:
      context: ./backend
      args:
        POETRY_PARAMS: "--no-dev"
    entrypoint: ./entrypoint.test.sh
    restart: "no"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=False
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - default

  db:
    restart: "no"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - default

  redis:
    restart: "no"
    networks:
      - default

volumes:
  static:
  redisdata:
  postgresdata:
  nuxt:
  nginx_cache:
  natsdata:
