# Generated by Django 4.2 on 2024-06-25 15:59

import common.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RequestCoordination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Согласование заявки",
                "verbose_name_plural": "Согласования заявок",
            },
        ),
        migrations.CreateModel(
            name="RequestState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Состояние заявки",
                "verbose_name_plural": "Состояния заявок",
            },
        ),
        migrations.CreateModel(
            name="RequestStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Статус заявки",
                "verbose_name_plural": "Статусы заявок",
            },
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=9, verbose_name="Номер заявки")),
                ("batch", models.CharField(verbose_name="ID пакета")),
                (
                    "is_duplicate",
                    models.BooleanField(
                        default=False, verbose_name="Является дубликатом"
                    ),
                ),
                (
                    "author_name",
                    models.CharField(max_length=255, verbose_name="Автор заявки"),
                ),
                (
                    "file_name",
                    models.CharField(
                        max_length=255,
                        validators=[common.validators.validate_file_extension],
                        verbose_name="Имя файла",
                    ),
                ),
                ("created", models.DateTimeField(verbose_name="Время создания")),
                (
                    "finished",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время окончания"
                    ),
                ),
                (
                    "handle_time",
                    models.DurationField(
                        null=True, verbose_name="Время от создания до конца обработки"
                    ),
                ),
                (
                    "material_full_name",
                    models.TextField(verbose_name="Полное наименование изначальное"),
                ),
                (
                    "technical_documentation",
                    models.CharField(max_length=128, verbose_name="НТД"),
                ),
                (
                    "coordination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requests",
                        to="request.requestcoordination",
                        verbose_name="Согласование",
                    ),
                ),
                (
                    "duplicate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicates",
                        to="request.request",
                        verbose_name="Дубликат заявки",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requests",
                        to="request.requeststate",
                        verbose_name="Состояние",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="properties",
                        to="request.requeststatus",
                        verbose_name="Статус",
                    ),
                ),
            ],
        ),
    ]
